# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: pratik.
email: NA
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# social media links
twitter_username: pratikshah
github_username:  pratikmshah
linkedin_username: pratikmshah
instagram_username: pratikshah_
aboutme: "https://about.me/pratikshah"

# project links
prism-demo: "http://prism-dbc.herokuapp.com/"
prism-src: "https://github.com/pratikmshah/prism"
yeeld-demo: "http://yeeld.herokuapp.com/"
yeeld-src: "https://github.com/pratikmshah/yeeld"
trade: "/tradelytics/index.html"
snowball: "/tradelytics/apps/snowball/snowball.html"
numbers: "/tradelytics/apps/numbers/numbers.html"

# about me links
resume:
resume-pdf:

# Build settings
markdown: kramdown

# Default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: programming
      permalink: /blog/:title
      layout: "post"
      comments: true
