var watchlist = 'watchlist';
var ETF = {
  XLY:"AMZN,HD,DIS,CMCSA,NFLX,MCD,NKE,BKNG,LOW,SBUX,TJX,CHTR,GM,FOXA,TGT,F,MAR,ROST,VFC,YUM,DG,APTV,ORLY,CCL,HLT,DLTR,FOX,CBS,AZO,BBY,RCL,OMC,MGM,EXPE,LEN,DHI,ULTA,GPC,MHK,TIF,TPR,DRI,KMX,WYNN,NWL,KSS,M,PVH,CMG,HAS,AAP,LKQ,NCLH,KORS,TSCO,VIAB,WHR,BWA,DISCK,IPG,PHM,HBI,LB,RL,GRMN,HOG,DISH,GPS,TRIP,JWN,LEG,FL,NWSA,MAT,GT,HRB,DISCA,UAA,UA,NWS",

  XLP:"PG,KO,PEP,PM,WMT,COST,MO,MDLZ,CL,WBA,KMB,STZ,KHC,SYY,EL,ADM,GIS,MNST,KR,TSN,K,CLX,CAG,MKC,BF.b,CHD,HSY,SJM,TAP,HRL,CPB,COTY",

  XLE:"XOM,CVX,SLB,EOG,COP,OXY,PSX,VLO,HAL,APC,KMI,MPC,PXD,OKE,CXO,WMB,DVN,ANDV,MRO,APA,HES,NBL,NOV,EQT,BHGE,FTI,HFC,COG,XEC,HP,NFX",

  XLF:"JPM,BRK.b,BAC,WFC,C,GS,USB,AXP,MS,PNC,SCHW,CB,BLK,CME,SPGI,BK,AIG,COF,MET,MMC,ICE,PRU,BBT,AON,PGR,TRV,AFL,STI,ALL,STT,MCO,TROW,DFS,MTB,SYF,NTRS,KEY,WLTW,AMP,RF,FITB,CFG,HIG,HBAN,CMA,SIVB,ETFC,MSCI,XL,PFG,LNC,L,AJG,RJF,CBOE,NDAQ,CINF,IVZ,ZION,BEN,RE,TMK,UNM,AMG,JEF,PBCT,AIZ,BHF",

  XLV:"JNJ,UNH,PFE,MRK,ABBV,AMGN,MDT,ABT,GILD,BMY,TMO,LLY,BIIB,CVS,BDX,ANTM,DHR,AET,CELG,ISRG,AGN,SYK,BSX,ILMN,VRTX,HUM,CI,ESRX,ZTS,BAX,EW,HCA,ALXN,REGN,CNC,MCK,ALGN,ZBH,IDXX,A,CERN,LH,MYL,IQV,ABMD,DGX,WAT,RMD,CAH,MTD,ABC,COO,INCY,HSIC,HOLX,VAR,XRAY,DVA,PRGO,UHS,PKI,NKTR,EVHC",

  XLI:"BA,MMM,HON,GE,UNP,UTX,CAT,LMT,UPS,CSX,RTN,FDX,NOC,GD,NSC,ITW,DE,EMR,ETN,DAL,JCI,WM,ROP,LUV,FTV,IR,COL,PCAR,SWK,PH,ROK,CMI,UAL,INFO,TDG,HRS,CTAS,GWW,VRSK,TXT,AME,FAST,LLL,AAL,EFX,RSG,EXPD,CHRW,XYL,URI,DOV,MAS,CPRT,KSU,JBHT,NLSN,HII,SNA,AOS,RHI,FBHS,JEC,ARNC,ALLE,ALK,PNR,FLR,SRCL,FLS,PWR",

  XLB:"DWDP,PX,ECL,LYB,APD,SHW,PPG,IP,FCX,NUE,NEM,VMC,WRK,EMN,MLM,BLL,FMC,PKG,ALB,IFF,CF,MOS,AVY,SEE",

  XLRE:"AMT,SPG,CCI,EQIX,PLD,PSA,WY,DLR,WELL,AVB,EQR,VTR,BXP,SBAC,O,HST,ESS,CBRE,GGP,ARE,VNO,HCP,EXR,MAA,DRE,UDR,IRM,FRT,REG,SLG,KIM,AIV,MAC",

  XLK:"AAPL,MSFT,FB,GOOG,GOOGL,V,INTC,T,VZ,CSCO,MA,NVDA,ORCL,ADBE,IBM,TXN,ACN,CRM,PYPL,QCOM,AVGO,MU,ADP,ATVI,INTU,CTSH,AMAT,EA,HPQ,ADI,FIS,TEL,EBAY,FISV,ADSK,LRCX,TWTR,APH,RHT,DXC,GLW,HPE,PAYX,WDC,MCHP,NTAP,MSI,FLT,GPN,CTL,XLNX,SWKS,KLAC,STX,TSS,ANSS,TTWO,CTXS,VRSN,BR,AKAM,CA,SYMC,SNPS,AMD,IT,CDNS,ADS,FFIV,JNPR,QRVO,WU,IPGP,FLIR,XRX",

  XLU:"NEE,DUK,SO,D,EXC,AEP,SRE,PEG,ED,XEL,PCG,EIX,WEC,PPL,DTE,ES,FE,AWK,EVRG,AEE,ETR,CMS,CNP,LNT,NRG,PNW,NI,AES,SCG",

  XTL:"NTGR,VG,NTCT,VSAT,CTL,MSI,PANW,CIEN,VIAV,S,ZAYO,UBNT,VZ,TMUS,ACIA,FNSR,EXTR,COMM,IDCC,ANET,OCLR,LITE,JNPR,ARRS,INFN,CSCO,FFIV,CCOI,AAOI,T,TDS,SATS,PLT,IRDM,CASA,CNSL,FTR,WIFI,ADTN,CBB,CAMP,SHEN,CMTL,ORBC,ATNI,USM",

  XTH:"NTAP,BDC,DDD,VSH,ITRI,FIT,STX,KN,GLW,DLB,LFUS,EFII,NATI,PAY,TRMB,ROG,COHR,KEYS,NCR,AAPL,FLIR,DBD,PSTG,HPQ,APH,HPE,CGNX,WDC,IIVI,ZBRA,XRX,ESIO,NOVT,OSIS,SMCI,CTRL,CRAY,BMI,USAT,FARO,IMMR,MTSC,AVX,MLAB",

  XSW:"ACXM,CA,EGHT,FSCT,QLYS,SYNT,IMPV,SQ,BLKB,FDC,TTWO,NUAN,DATA,PTC,EPAY,GLUU,RNG,EBIX,PCTY,ULTI,CRM,MANH,MANT,VRNT,PRO,ATVI,FTNT,EPAM,FLT,BL,BKI,WDAY,EA,DVMT,CTSH,GWRE,NOW,ZEN,ACIW,UIS,EXLS,TVPT,SSNC,MSTR,PAYC,CVG,EVBG,PFPT,CACI,WP,TDC,RP,CATM,VRTU,JKHY,ANSS,SYKE,INTU,LDOS,SABR,MMS,BAH,V,FICO,WEX,HUBS,PYPL,PAYX,AZPN,MA,CDK,TYL,ACN,RPD,MSFT,EVTC,SNAP,CDNS,ADBE,FISV,TSS,FIS,ADS,IBM,SWCH,DXC,PRGS,CTXS,VRNS,VMW,SNPS,IT,ADP,AVYA,PRFT,ORCL,FEYE,EEFT,CLGX,GPN,SAIL,SYMC,ELLI,ADSK,BR,APPN,G,CVLT,CSGS,SAIC,WK,ZNGA,ALTR,WU,PRSP,PEGA,TYPE,EVRI,CNDT,TIVO,SPLK,RHT,MODN,OSPN,PSDO,ATEN,TTEC",

  SMH:"INTC,TSM,NVDA,ASML,QCOM,TXN,MU,ADI,NXPI,LRCX,AMAT,AVGO,MCHP,MXIM,SWKS,AMD,XLNX,KLAC,MRVL,CDNS,ON,TER,QRVO,OLED,STM",

  XRT:"CVNA,RCII,W,MNRO,NTRI,DSW,OSTK,CASY,KR,MUSA,SIG,AAP,TRIP,BBY,AMZN,PRTY,COST,FIVE,RAD,AZO,DLTR,ORLY,EXPE,KMX,SVU,GES,SFM,DG,WMT,PETS,TSCO,OLLI,JWN,TIF,TJX,BIG,GME,QRTEA,WBA,ANF,CONN,AEO,ROST,ULTA,GRPN,URBN,CWH,NFLX,SBH,TGT,AN,BURL,MIK,CHS,CAL,M,PAG,GPS,EXPR,HIBB,KSS,LEXEA,LAD,DKS,PLCE,BKNG,SFLY,GPI,JCP,DDS,FL,LB,ABG,EYE,ODP,GCO,BKE,PSMT,TLRD,BOOT,LTRPA,ZUMZ,CATO,HZO,WMK,IMKTA,SAH,CTRN",

  XWEB:"ETSY,W,WEB,NTRI,INST,OSTK,AYX,CARS,MDB,TRUE,HDP,FB,MB,OKTA,APTI,COUP,CSOD,TRIP,TWLO,GDDY,VRSN,YEXT,AMZN,GRUB,P,TTD,NEWR,LEXEA,GOOG,EXPE,QTWO,TWTR,EGOV,SSTK,BNFT,PETS,ENV,ANGI,STMP,QRTEA,NTNX,BOX,LOGM,GRPN,NFLX,JCOM,SPSC,Z,QNST,GTT,AKAM,ALRM,IAC,BCOR,TWOU,FIVN,LTRPA,YELP,CARB,BKNG,MTCH,SFLY,CLDR,LPSN,EBAY,GOGO,APPF,QUOT,CISN,EIGI,LLNW",

  HACK:"QLYS,IMPV,CHKP,PANW,CSCO,FTNT,PFPT,CYBR,CACI,JNPR,SYMC,AKAM,FEYE,CVLT,SAIC,SPLK,CARB,SOPH,VRSN,OKTA,FSCT,NTCT,RDWR,FFIV,LDOS,MANT,VRNT,BAH,EVBG,RPD,VRNS,ZS,MIME,OSPN,SCWX,CBLK,KEYW,ATEN,MOBL,ZIXI",

  XTN:"UAL,MIC,R,SAVE,UHAL,LUV,JBLU,NSC,GWR,CSX,ALK,CHRW,HUBG,WERN,KSU,DAL,HA,UNP,LSTR,UPS,ALGT,EXPD,SAIA,JBHT,KEX,KNX,SNDR,ODFL,SKYW,FDX,AAWW,XPO,AAL,HTZ,CAR,ATSG,ECHO,FWRD,HTLD,ARCB,MRTN,MATX,DSKE",

  XHE:"TNDM,INGN,AXGN,MMSI,IDXX,DXCM,ITGR,QDEL,HOLX,ISRG,LIVN,ALGN,COO,BDX,IRTC,XRAY,BSX,EW,HAE,NEOG,GKOS,STE,ICUI,ABMD,WST,NUVA,WMGI,RMD,CNMD,MDT,ABT,ABAX,DHR,MASI,BAX,HRC,AVNS,NXTM,ZBH,TFX,IART,OSUR,OFIX,SYK,BABY,CUTR,VAR,CMD,GMED,PODD,PEN,HSKA,TCMD,VREX,CERS,NVRO,CSII,LNTH,ATRI,LMAT,IVC,TRXC,SIEN,ANIK,ATRC,KTWO,ANGO,VIVO,CRY,ARAY,ELGX,GNMK",

  XES:"DRQ,AROC,OII,PUMP,ESV,RES,NE,NOV,DO,OIS,RIG,SPN,SLB,WFT,HAL,FTI,BHGE,APY,HP,FRAC,PTEN,RDC,CLB,CJ,MDR,SLCA,NBR,FET,UNT,WHD,HLX,CKH,BRS,WTTR,CVIA,FI,NR,EXTN,TDW,TTI,MTRX",

  XME:"CLF,AKS,CDE,RGLD,X,NUE,NEM,RS,BTU,ARCH,ATI,STLD,HCC,CMC,FCX,AA,CRS,CMP,CENX,KALU,HL,CEIX,WOR,SCHN,MTRN,TMST,SXC,MUX,HAYN",

  XBI:"SRPT,HRTX,ICPT,VRTX,REGN,BIIB,LGND,FMI,ALXN,SAGE,BMRN,UTHR,ESPR,EXEL,SGEN,PBYI,CELG,IMMU,CLVS,GILD,EXAS,ALNY,ONCE,NBIX,AMGN,ANAB,IONS,FOLD,INCY,NTLA,LOXO,FGEN,DVAX,BLUE,SPPI,ACAD,MDGL,AGIO,BPMC,IMGN,ARRY,PTLA,ALKS,RARE,EDIT,TSRO,ARNA,SGMO,GBT,PTCT,ABBV,RDUS,IRWD,ATRA,MYGN,OPK,ADMS,AIMT,EBS,RGNX,XON,GERN,MNTA,ENTA,PRTA,ALDR,ARWR,HALO,FLXN,SRNE,INSM,BHVN,XLRN,AMAG,ABEO,LJPC,EGRX,IOVA,MRTX,TGTX,BOLD,GTHX,KPTI,RGEN,VNDA,CTMX,MDXG,CARA,CHRS,XNCR,NVAX,GLYC,ACOR,RTRX,FPRX,AKAO,VCEL,PGNX,MGNX,VYGR,SGYP,RIGL,GHDX,EPZM,FATE,LXRX,KURA,APLS,BCRX,AKBA,ACHN,KERX,INO,PDLI,NVTA,ATNX,STML,ZIOP,CYTK",

  XAR:"AAXN,ARNC,TDG,UTX,HEI,SPR,HII,LLL,KTOS,KLXI,LMT,TDY,COL,HRS,MRCY,BWXT,TXT,CW,BA,GD,NOC,AJRD,HXL,RTN,AVAV,ESL,TGI,CUB,AIR,MOG.A,WAIR,NPK,ATRO,EGL,KEYW",

  XHS:"MOH,AMED,CNC,LHCG,WCG,AMN,ANTM,PINC,OMI,HUM,ACHC,EHC,PDCO,AET,DGX,BEAT,HSIC,BKD,HQY,HCA,TVTY,MGLN,EVHC,UNH,DPLO,CHE,CVS,LH,ABC,DVA,CI,ESRX,UHS,THC,MD,MCK,CAH,LPNT,SEM,ENSG,CYH,USPH,PRSC,GTS,CSU,CCRN,BIOS,CRVL",

  XPH:"MNK,BMY,LLY,PRGO,PFE,AGN,JNJ,JAZZ,MRK,ZTS,NKTR,MYL,ENDP,CTLT,AKRX,SUPN,MDCO,PBH,HZNP,PCRX,ZGNX,ECYT,MYOK,AMRX,AERI,CORT,OMER,INVA,TXMD,CBAY,DEPO,RVNC,COLL,LCI,XENT,ITCI,ASMB,TBPH,RETA,ANIP,WVE,ACRS,PAHC,AMPH",

  PBJ:"YUM,SHAK,SYY,MDLZ,KHC,GIS,STZ,TSN,BF/B,SAM,KR,USFD,PFGC,NOMD,LW,CVGW,HRL,ADM,MGPI,PF,FLO,SFM,SJM,WMK,CALM,CAG,SEB,UNFI,SAFM,PPC",

  PEJ:"HLT,BKNG,MAR,YUM,LVS,WYNN,WWE,MSG,BXG,BJRI,SHAK,TXRH,EAT,DPZ,DENN,RRR,AMCX,BYD,H,PNK,CHDN,USFD,PFGC,DAL,JBLU,SKYW,HA,CPA,GRUB",

  ACT:"SAM,STZ,ABBV,RICK,TPB,PM,BF/B,MGPI,CTLT,MO,ABT,BTI,IMBBY,BREW,DEO,CCU,BJRI,ABEV,DRI,CRBP,VGR,UVV,HEINY,VCOYY,BUD,INSY,SMG,KNBWY,PDRDY,TAP,PLAY,LVMUY,AOI,FMX,BORN",

  XHB:"MHK,WHR,HD,LEN,OC,JCI,LOW,WSM,MAS,NVR,LII,DHI,FBHS,PHM,TOL,BBBY,ALLE,LEG,AOS,USG,AAN,LGIH,BLD,TMHC,AWI,TPH,TREX,MDC,HELE,IBP,SSD,WLH,CVCO,CCS,MHO",

  ITB:"LEN,DHI,NVR,PHM,TOL,HD,LOW,BLD,SHW,TPH,TMHC,KBH,MHK,CVCO,MAS,MTH,LII,OC,FBHS,LEG,WSO,MDC,EXP,TREX,USG,IBP,LPX,BECN,LGIH,SSD,DOOR,JELD,FND,UFPI,BLDR,PGTI,MHO,CCS,LL,AMWD,LENB,ETH,WLH,NX,TTS,BZH,HOV",

  ARKK:"TSLA,SSYS,NTLA,ILMN,TWTR,NVTA,BIDU,EDIT,SQ,TER,AMZN,LC,AAPL,NSTG,JD,NFLX,CERS,NVDA,APTV,TSM,BLUE,ATHN,TCEHY,RHT,MDSO,CRM,XLNX,MELI,VCYT,SPOT,RDFN,MCRB,CRSP,PACB,SPLK,SYRS,MTLS,BABA,CGEN,ONVO,XONE,GBTC,MGTI",

  MTUM:"AMZN,MSFT,V,BA,MA,JPM,CSCO,INTC,NFLX,ADBE,HD,NVDA,ABBV,NKE,ABT,COST,PYPL,TXN,ACN,ISRG,VLO,SPGI,INTU,CAT,SCHW,ZTS,CME,EL,RTN,PSX,ANTM,PGR,FOXA,BLK,NOC,SYK,RHT,MU,MAR,NOW,TROW,TGT,SQ,ROST,VFC,ABMD,TWTR,NTAP,MCO,ALGN,PXD,HCA,YUM,ANDV,FISV,FOX,ETFC,DG,HFC,PANW,MSCI,BBY,FLT,BR,VRSK,CPRT,GWW,LULU,MSI,HLT,BFB,SIVB,HPE,SPLK,CTAS,HRS,CSGP,TRU,ANSS,ANET,RF,XL,IAC,TSS,MELI,AMTD,GPN,STX,GDDY,TPR,CXO,KSS,CTXS,NKTR,PVH,CMA,XPO,XYL,CBRE,NDAQ,KORS,DPZ,FFIV,CHRW,AKAM,SSNC,FTNT,AJG,TFX,FANG,VST,JKHY,ODFL,JLL,VOYA,IEX,IPGP,FLIR,SPR,CLR,ALV,FLR,WLK,HP",

  IPAY:"V,PYPL,MA,AXP,FIS,FISV,SQ,WP,DFS,FDC,FLT,GPN,TSS,WU,WEX,PAGS,GDOT,EEFT,EVOP,NCR,ACIW,PAY,EVTC,QIWI,USAT,8584 JP,UEPS,MGI",

  GAMR:"TTWO,GLUU,ATVI,EA,GME,ZNGA,CYOU,AMD,GOOG,SNE,LOGI,MSFT,AAPL,NVDA,INTC,NTES,QCOM,YY,HEAR,MOMO,SINA,SOHU,CMCM,VUZI,IMMR,KOPN,GRVY",

  MJ:"CRON,GWPH,WEED,CRBP,TPB,XXII,INSY,CARA,PM,MO,UVV,ARNA,SMG,SWM,VGR",

  AIEQ:"GOOGL,FCE/A,TXN,RDN,NDAQ,AMZN,MCHP,STI,WMT,BYD,SEIC,FB,HWC,AAN,ABBV,CIT,ALLY,MMM,PAH,HII,TRGP,AMP,SSNC,FANG,CTSH,LPLA,TECD,MKL,XRX,BF/B,CBS,CTLT,AAPL,BGCP,VVV,AMGN,EA,TCBI,PF,SNPS,MHK,DXC,BKU,CIEN,BAX,COLL,AVGO,SIVB,THO,ROP,FL,TMO,NVDA,SAVE,ASGN,AET,ANET,IT,TGNA,NDSN,LVS,BLUE,ISRG,ZBRA,NKTR,SWKS,COST,HQY,NOW,SPR,EW,GD,HTH,KMX,LDOS,PVAC,MMC,URI,TER,ADM,MCK,CHTR,ISBC,CRM,ITCI,OC,LXU,WAL,ANTM,ROL,CBAY,BERY,SYX,CDW,JBLU,SKYW,CFG,ZNGA"
}

$(function() {

  onLoad();

  // execute and return charts for stock tickers from text box
  $('#run').on('click', function() {
    var value = $.trim($("#stock-ticker").val());

    if(value.length) {
      var tickers = parseTickerSymbols();
      var copyTickers = tickers.slice();
      tickers = createUrls(tickers);
      displayCharts(tickers, copyTickers);
    }
  });

  // erase input box on click of x button
  $('#erase').on('click', function() {
    $('#stock-ticker').val('');
    $('#erase').hide();
  });

  // check values inside textbox and toggle cancel button
  $('#search').on('change paste keyup', function() {
    if($('#stock-ticker').val().length) {
      $('#erase').show();
    } else {
      $('#erase').hide();
    }
  });

  // parse user text box symbols
  function parseTickerSymbols() {
    return  $('#stock-ticker').val().split(',');
  }

  // construct chart urls
  function createUrls(arr) {
    const URL_BASE = "https://finviz.com/chart.ashx?t=";
    const URL_CHART_SPEC = "&ty=c&ta=1&p=d&s=l";

    for(var i = 0; i < arr.length; i++) {
      arr[i] = URL_BASE + arr[i].toUpperCase() + URL_CHART_SPEC;
    }

    return arr;
  }

  // display charts onto the page
  function displayCharts(arr, sym) {
    $chart = $('#charts');
    $chart.empty();
    $('#save').show();

    for (var i = 0; i < arr.length; i++) {
      $chart.append('<div class="chart-container"> <img src=' + arr[i] + ' class="chart" data-border-color="black" /> <input type="checkbox"  name="watchlist" value=' + sym[i].toUpperCase() + '> </div>');
    }

  }

  // on double click change border color to green or black
  $('#charts').on('click', '.chart-container img', function() {
    $this = $(this);

    if($this.attr('data-border-color') === 'black') {
      $this.attr('data-border-color', 'green');
      $this.css('border-color', '#7CFC00');
      $this.next().prop("checked", true);
    } else {
      $this.attr('data-border-color', 'black');
      $this.css('border-color', 'black');
      $this.next().prop("checked", false);
    }

  });

  // save watchlist
  $('#save').on('click', function() {
    if($("input:checkbox:checked").length) {
      getWatchlist();
    }
  });


  // generate watchlist file
  function getWatchlist() {
    var tickers = parseWatchlist();
    var file = new Blob(tickers, { type: "text/plain;charset=utf-8" });
    saveAs(file, watchlist + ".txt");
  }

  // parse watchlist
  function parseWatchlist() {
    var tickers = $("input:checkbox:checked").map(function() {
      return $(this).val() + ',';
    }).get();

    return tickers;
  }

  // set watchlist name
  $('#scans li a').on('click', function() {
    watchlist = $(this).attr("data-text");
  });

  $('#etf-scans li a').on('click', function() {
    watchlist = $(this).attr("data-text");
  });

  // scroll top
  $(document).scroll(function() {
    if($(document).scrollTop() > 100) {
      $("button#scroll-top").css("display", "block");
    } else {
      $("button#scroll-top").css("display", "none");
    }
  });

  $("#scroll-top").click(function() {
    $("html, body").animate({ scrollTop: 0 }, "slow");
  });


  // ETFS
  $('#etf-scans li a').on('click', function(e) {
    $('#stock-ticker').val('');
    $('#stock-ticker').val(ETF[$(this).attr("data-text")]);
    $('#erase').show();
  });

});

// hide save button, reset values on texbox when page loads
function onLoad() {
  $('#save').hide();
  $('#stock-ticker').val('');
  $('#erase').hide();
}
